kufu/eslint-config-smarthr

- package.json
- yarn.lock
When using `eslint-config-smarthr`, an error occurred due to the absence of `@typescript-eslint /parser`.
> Add @typescript-eslint/parser

- configs/eslint.js
- package.json
- test/fixtures/Counter.tsx
BREAKING CHANGE: ESLint v5 is no longer supported
`no-console` has been removed from `eslint:recommended` so we don't have to disable the rule explicitly.
> feat: support ESLint v6

- yarn.lock
Recreated yarn.lock file to fix vulnerabilities that detected by `yarn audit`
```
~/projects/eslint-config-smarthr recreate-yarn-lock
❯ yarn audit
yarn audit v1.17.3
0 vulnerabilities found - Packages audited: 876530
✨  Done in 1.08s.
```
> chore: recreate yarn.lock file to fix yarn audit

- configs/typescript.js
- package.json
- yarn.lock
BREAKING CHANGE: This adds some rules enabled by plugin:@typescript-eslint/recommended
See the rules below.
https://github.com/typescript-eslint/typescript-eslint/blob/v2.0.0/packages/eslint-plugin/src/configs/recommended.json
> deps: update @typescript-eslint to v2

- index.js
- test/__snapshots__/run.test.js.snap
`no-shadow` の rule 設定に不備があり `enum` で lint エラーになる現象を修正
参考：https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md
> fix: fix no-shadow settings

- .eslintrc.js
- configs/eslint.js
- configs/prettier.js
- index.js
- test/__snapshots__/run.test.js.snap
- test/fixtures/Counter.tsx
This PR changed the order of prettier config, and it broke some existing rules, which I want to fix.
https://github.com/kufu/eslint-config-smarthr/pull/292
To be specific, the config for semicolon was conflicting between `@typescript-eslint` and `eslint-config-prettier`
- cut out the prettier settings as a separate file to let it extended at the last https://github.com/kufu/eslint-config-smarthr/commit/dec908c25a831affcd963f6da2894e566c43cfeb
- updated the snapshot https://github.com/kufu/eslint-config-smarthr/commit/97c4e0df9fdf4b9878a84b8e01e6cff411f75bd8
- the deleted line was a duplicated thing (the second `"prettier/prettier"` and the deleted `"jsx-quotes"` were indicating the same error)
- add some code to the `Counter` component to test semicolon config …
> fix: apply eslint-config-prettier correctly

- .circleci/config.yml
- package.json
- renovate.json
- yarn.lock
依存ライブラリを諸々アップデートして eslint-config-smarthr を ESLint v8 に対応させたい！
- 3626b175d898343291744a790b1822760d7014c9 CIのdockerのバージョンが残念な感じになっていたので修正 & アップデート
- 1d031894b45e927fcb5bf034562ab22dd8d41bf1 👆はrenovateのPRが原因だったので対象をnpmに限定して対策
- c2624a80522cb319d070107c10886ba172f8a63b 依存ライブラリのバージョンを一斉age
- 703222256b96232a9a2348a108ebcf2c9d2840f0 Jestがpackage.jsonのexportsを参照してくれない問題があるため、moduleNameMapperを書いて暫定対処
<details>
<summary>$ yarn test でこんなエラーが発生していた。</summary>
```
[diescake:eslint-config-smarthr]$ yarn test
yarn run v1.22.10
$ jest
FAIL  test/run.test.js
fixtures
✕ should match the snapshot (596 ms)
● fixtures › should match the snapshot
Failed to load plugin '@typescript-eslint' declared in '--config » ./configs/typescript.js': Cannot find module 'eslint/use-at-your-own-risk' from …
```
> feat!: support ESLint v8

- CHANGELOG.md
- package.json
`eslint-plugin-react-hooks`v4.2.0をv4.3.0に上げるためのパッチアップデートです。
https://github.com/facebook/react/issues/22545
> chore(release): 6.0.1

- CHANGELOG.md
- package.json
```
```
がCHANGLOGに誤追記されるので後で修正する
> chore(release): 6.0.3

- yarn.lock
- eslint-plugin-smarthrを更新します
- format-import-path: import path に `xxxx/index` のように index.ts などを指定している場合、自動的に省略する処理を追加
- prohibit-import:  `import { hoge } from 'fuga'` 以外にも `import hoge from 'fuga'` 記法にも対応できるように修正
- redundant-name: 修正対象の指定条件ミスを修正
修正詳細
- https://github.com/kufu/eslint-plugin-smarthr/commits/main
> update: eslint-config-smarthr

- package.json
- yarn.lock
- smarthr/redundant-name の allowedNames が一部無視されるバグが修正されます
> chore: update eslint-plugin-smarthr

- index.js
- package.json
- tsconfig.json
- yarn.lock
以下のルールを初期値でerrorにします
- smarthr/a11y-clickable-element-has-text
- smarthr/a11y-image-has-alt-attribute
- smarthr/a11y-trigger-has-button
- smarthr/best-practice-for-date
- smarthr/jsx-start-with-spread-attributes
- smarthr/prohibit-export-array-type
- smarthr/require-barrel-import
> feat: eslint-plugin-smarthrのおすすめルールをdefault errorにする

- index.js
- package.json
- yarn.lock
- eslint-plugin-smarthrを更新し、入力要素にplaceholderが使われていると他の手段（ヒント用の要素を作成 or tooltip）を利用することを促すルールをデフォルトwarnで導入するようにしました
> feat: update eslint-plugin-smarthr@v0.2.8

- package.json
- yarn.lock
- `a11y-anchor-has-href-attribute` ルールに nextjs, react_routerを利用している場合向けのオプションを追加します
> feat: update eslint-plugin-smarthr (a11y-anchor-has-href-attribute に nextjs, react_router オプションを追加)

- .circleci/config.yml
- package.json
- yarn.lock
- https://github.com/kufu/eslint-config-smarthr/pull/621 のCI落ちを直してマージしたい！
- typescript-eslint monorepo v6にて、Node.js v14がサポートされなくなったためCIからv14を外しつつ、v18を追加した
- clrcleciのimageがlegacy image（`circleci/`）のままだったため、現行のimage（`cimg/`）に変更した
- [majorバージョンのみの指定ができなくなったっぽい](https://github.com/CircleCI-Public/cimg-node/issues/130)ので、minorバージョンまで指定したよ
> typescript-eslintのアップデートをしつつ、CircleCIのnodeのimageを更新したい

- package.json
現状の `peerDependencies` では `"eslint-plugin-smarthr": "^0.1.1 || ^0.2.0 || ^0.3.0"` のような幅を持たせた指定方法になっています。
しかし、  `'smarthr/a11y-heading-in-sectioning-content': 'error',` といったルールで指定されている `a11-heading-in-sectioning-content` が eslint-plugin-smarhr に登場するのは 0.3.2 からであり、それよりも前のバージョンで利用しようとすると `Definition for rule 'smarthr/a11y-heading-in-sectioning-content' was not found` となり落ちます。
問題が起きないバージョンを指定するよう peerDependencies の内容を修正しました。
> peerDependencies で利用できないバージョンを指定していた問題を修正

- README.md
- configs/prettier.js
- package.json
- test/__snapshots__/run.test.js.snap
- yarn.lock
eslint-config-smarthr では eslint-plugin-prettier を利用していますが、現在では利用が推奨されなくなっています。
[Integrating with Linters · Prettier](https://prettier.io/docs/en/integrating-with-linters.html#notes)
eslint-plugin-prettier の利用を廃止し、直接 prettier を呼び出すような方針を提案します。
> 推奨されなくなった eslint-plugin-prettier の利用の廃止

- CHANGELOG.md
- package.json
- yarn.lock
* a11y-heading-in-sectioning-contentに"SectioningContent内のsmarthr-ui/Heading系コンポーネントにtag属性が設定されている場合エラー"になる機能を追加 ([#85](https://github.com/kufu/eslint-plugin-smarthr/issues/85)) ([c34b4f4](https://github.com/kufu/eslint-plugin-smarthr/commit/c34b4f43da89d7baf48c2536dcd381327064ef75))
* a11y-image-has-alt-attributeでaria-describedbyが設定されている場合、エラーにならないように修正 ([#84](https://github.com/kufu/eslint-plugin-smarthr/issues/84)) ([046ee0f](https://github.com/kufu/eslint-plugin-smarthr/commit/046ee0f082381627343371235102304a3f2a0938))
> Update eslint plugin smarthr

- index.js
- package.json
- yarn.lock
* a11y-input-in-form-controlを追加する ([#98](https://github.com/kufu/eslint-plugin-smarthr/issues/98)) ([fb7e77d](https://github.com/kufu/eslint-plugin-smarthr/commit/fb7e77d8c3ac73f57425d094a240d998ff78a51d))
* a11y-prohibit-useless-sectioning-fragmentを追加する ([#106](https://github.com/kufu/eslint-plugin-smarthr/issues/106)) ([994c040](https://github.com/kufu/eslint-plugin-smarthr/commit/994c04027892a5fe50fb71ba8b5941401f12c02c))
> feat: eslint-plugin-smarthrをupdate

- package.json
- yarn.lock
- a11y-input-in-form-control ルールに置いて、XxxxRadioButtons, YyyCheckBoxes などがラベル付きの複数の入力要素をもつコンポーネントとして正しく扱われるようになります
> feat: eslint-plugin-smarthr@0.4.0

- index.js
- package.json
- yarn.lock
* a11y-numbered-text-within-olを追加する ([#105](https://github.com/kufu/eslint-plugin-smarthr/issues/105)) ([167b92f](https://github.com/kufu/eslint-plugin-smarthr/commit/167b92f0f29db8ee9a446d25e09e04a7b11ce340))
* ComboBoxなどのinputAttributesでtitle属性が指定された場合、擬似的にラベルが付いていると判定するように修正 ([#113](https://github.com/kufu/eslint-plugin-smarthr/issues/113)) ([5f3b594](https://github.com/kufu/eslint-plugin-smarthr/commit/5f3b5943ec64a18d094a9c66627ad1db2bbabe08))
> feat: eslint-plugin-smarthrをv0.4.1にupdateする

- index.js
- package.json
- test/__snapshots__/run.test.js.snap
- yarn.lock
- button要素にtype属性の設定を促すルールをwarnで追加
- https://github.com/kufu/eslint-plugin-smarthr/pull/115
- a11y-numbered-text-within-olを調整し、誤検知されないようにする
- https://github.com/kufu/eslint-plugin-smarthr/pull/117
> feat: eslint-plugin-smarthr@v0.4.2にupdate

- README.md
- package.json
- #821
にて議論しましたが、やはり `eslint-config-smarthr` にとっては常に最新の `eslint-plugin-smarthr` を使用して欲しいという意図があると思うので、 `peerDependencies` から外して `dependencies` のみにします。
これによって、pnpm v9 であっても、最新の `eslint-config-smarthr` をインストールした場合はそこで定義されている最新の `eslint-plugin-smarthr` が使用されるようになります。
(pnpm v8 や yarn の場合は、`peerDependencies` と `dependencies` 両方定義してる場合に後者を優先してくれてたみたい)
> chore: eslint-plugin-smarthr を peerDependencies から外す

- index.js
- test/__snapshots__/run.test.js.snap
- a11y-prohibit-input-maxlength-attribute,a11y-replace-unreadable-symbol,best-practice-for-layoutsをdefault errorに変更します
> feat: a11y-prohibit-input-maxlength-attribute,a11y-replace-unreadable-symbol,best-practice-for-layoutsをdefault errorに変更

- package.json
- yarn.lock
typescript-eslint 関連パッケージのバージョンを v8 から v7 に戻す
v6.33.0 から v6.33.1 のパッチバージョンアップの中に、typescript-eslint のメジャーバージョンアップが紛れてしまい、利用者にとってはパッチバージョンを上げただけなのにCIが盛大に落ちて個別対応が必要という状況になってしまうため。
https://github.com/kufu/eslint-config-smarthr/compare/v6.33.0...v6.33.1
v6.33.0 時点の状態に package.json を戻す
v8 に上げる作業は、ESLint の v9 対応とセットでやるのが良さそう…？
> chore: typescript-eslint を v8 から v7 に戻す

- package.json
- yarn.lock
typescript-eslint 関連パッケージのバージョンを v7 から v8 にあげます
- https://github.com/kufu/eslint-config-smarthr/pull/867
にて、パッチバージョンでうっかりメジャーバージョンを上げてしまったのを戻したままの状態になっていたので、単体でバージョンアップします。
v8 系の最新版に変更する
このPRマージ後、eslint-config-smarthr v7 としてリリースする予定です。
**本当は eslint v9 対応とセットでやろうとも思ってましたが、typescript-eslint は eslint v8,v9 両方をサポートしてるので、問題の切り分けをしやすくするために分けて進めます。**
> chore: typescript-eslint を v8 にバージョンアップする
