- yarn.lock
- format-import-path に autoオプションを追加しました
- 相対パス、絶対パスのいずれかのより近い方を自動選択するようになります。
> update: format-import-path

- package.json
- yarn.lock
- eslint-plugin-smarrthr が npm に公開されたので差し替えます。
> update: eslint-plugin-smarthr

- package.json
- yarn.lock
- eslint-plugin-smarthrの更新を取り込みます
> chore: update eslint-plugin-smarthr

- index.js
- package.json
- yarn.lock
- eslint-plugin-smarthr を更新します。
> chore: update eslint-plugin-smarhtr

- package.json
- yarn.lock
- eslint-plugin-smarthrをv0.2.1にupdateします
- READMEが分割され、新規のruleが追加されました
> chore: update eslint-plugin-smarthr v0.2.1

- package.json
- yarn.lock
> chore: upate eslint-plugin-smarthr

- configs/eslint.js
- configs/react.js
- package.json
- yarn.lock
public repository なのでリンクは貼りませんが、10/20のフロントエンド MTG で話し合った内容に沿って追加しています。
- arrow-body-style
- https://eslint.org/docs/latest/rules/arrow-body-style
- dot-notation
- https://eslint.org/docs/latest/rules/dot-notation
- import/no-duplicates
- https://eslint.org/docs/latest/rules/no-duplicate-imports
- import/no-useless-path-segments
- https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-useless-path-segments.md
- import/order
- https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
- object-shorthand
- https://eslint.org/docs/latest/rules/object-shorthand
- react/jsx-fragments
- https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md
- react/jsx-no-useless-fragment
- …
> いくつかのルールを追加

- package.json
- yarn.lock
- eslint-plugin-smarthr を更新します
- svgタグ内のimageタグに対するaltチェックを除外する用になりました
- ComboBoxのplaceholderチェックが詳細になりました
- DatePickerのplaceholderチェックが追加されました
> feat: update eslint-plugin-smarthr@0.2.10

- index.js
- package.json
- yarn.lock
新規作成されたルール`trim-props`を有効化する設定を追加しました。
> feat: trim-propsルールを追加

- index.js
- package.json
- yarn.lock
- eslint-plugin-smarthrを更新します
- いくつかのルールで特定のオプションを指定するとエラーになる問題を修正
- https://github.com/kufu/eslint-plugin-smarthr/tree/main/rules/prohibit-path-within-template-literal で特定のパターンのコードをチェックするとエラーになる問題を修正
- 新規に追加された https://github.com/kufu/eslint-plugin-smarthr/tree/main/rules/a11y-radio-has-name-attribute をwarnで有効化します
> feat: update eslint-plugin-smarthr

- index.js
- package.json
- yarn.lock
- radioボタンのname属性チェックがinput全体に変更となったので対応
> feat: smarthr/a11y-radio-has-name-attribute を smarthr/a11y-input-has-name-attribute に切り替える

- index.js
- package.json
- yarn.lock
- a11y-anchor-has-href-attribute ルールをwarnで有効化します
> feat: a11y-anchor-has-href-attribute を有効にする

- index.js
- package.json
- yarn.lock
a11yに関するルールを error にします。
- a11y-anchor-has-href-attribute
- a11y-input-has-name-attribute
- a11y-prohibit-input-placeholder
> feat: a11yに関連するルールを warn -> error に変更

- index.js
- package.json
- yarn.lock
- `eslint-plugin-smarthr@0.2.25` にupdateします
> chore: update eslint-plugin-smarthr@v0.2.25

- package.json
- yarn.lock
- a11y-heading-in-sectioning-content の誤検知問題を修正します
> updae eslint-plugin-smarthr

- package.json
- yarn.lock
- https://github.com/kufu/eslint-plugin-smarthr/releases/tag/v0.3.8
> feat: eslint-plugin-smarthrをv0.3.8にupdate

- index.js
- package.json
- test/__snapshots__/run.test.js.snap
- yarn.lock
https://github.com/kufu/eslint-plugin-smarthr/pull/92
> feat: a11y-delegate-element-has-role-presantation を追加

- package.json
- yarn.lock
- a11y系コンポーネントで入力要素の拡張コンポーネントの判定をfunctionを使っている場合にも正しく判定できるように修正
> feat: update eslint-plugin-smarthr@0.3.27

- package.json
- yarn.lock
- 各ルールのオプションに設定できる値 `smart` を `allow-spread-attributes` に変更しました
> feat: update eslint-plugin-smarthr@0.5.0

- index.js
- package.json
- yarn.lock
- `smarthr/a11y-form-control-in-form` を追加
> feat: update smarthr/eslint-plugin-smarhtr@0.5.1

- README.md
README 上でのインストール手順にて、 `eslint-plugin-smarthr` もインストールするように追記しました。
> chore: eslint-plugin-smarthr も peerDependencies なので、README.md での案内に追記する

- package.json
- yarn.lock
https://github.com/kufu/eslint-plugin-smarthr/releases/tag/v0.5.11
> feat: update eslint-plugin-smarthr@0.5.11

- package.json
- yarn.lock
https://github.com/kufu/eslint-plugin-smarthr/releases/tag/v0.5.17
> feat: update eslint-plugin-smarthr@0.5.17
